#!/bin/bash

function send_notification() {
    echo "$1"
}

function assert_success() {
    "${@}"
    local status=${?}
    if [ ${status} -ne 0 ]; then
        send_notification "### Error ${status} at: ${BASH_LINENO[*]} ###"
        exit ${status}
    fi
}

app=gogs-rpi
version=0.11.91
username=insanusmokrassar

assert_success docker build -t $app:"$version" doicker
assert_success docker tag $app:"$version" $username/$app
assert_success docker push $username/$app
